// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjazVgTemaS83mjp-YxXs20rAxg2xArvU',
    appId: '1:850076040984:web:1d4041d85e24e981a4e86d',
    messagingSenderId: '850076040984',
    projectId: 'flutter-bootcamp-project-addcc',
    authDomain: 'flutter-bootcamp-project-addcc.firebaseapp.com',
    storageBucket: 'flutter-bootcamp-project-addcc.firebasestorage.app',
    measurementId: 'G-2LH17J2RST',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCu9BdicUqGMfwzWgc562ySV48MS-qySBY',
    appId: '1:850076040984:android:e689edc1607ec57fa4e86d',
    messagingSenderId: '850076040984',
    projectId: 'flutter-bootcamp-project-addcc',
    storageBucket: 'flutter-bootcamp-project-addcc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIaYY9jillsLKU1L4DAGBHgIbPPuT_0jA',
    appId: '1:850076040984:ios:2378b7b120fb80e0a4e86d',
    messagingSenderId: '850076040984',
    projectId: 'flutter-bootcamp-project-addcc',
    storageBucket: 'flutter-bootcamp-project-addcc.firebasestorage.app',
    iosBundleId: 'com.example.flutterBootcampProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIaYY9jillsLKU1L4DAGBHgIbPPuT_0jA',
    appId: '1:850076040984:ios:2378b7b120fb80e0a4e86d',
    messagingSenderId: '850076040984',
    projectId: 'flutter-bootcamp-project-addcc',
    storageBucket: 'flutter-bootcamp-project-addcc.firebasestorage.app',
    iosBundleId: 'com.example.flutterBootcampProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjazVgTemaS83mjp-YxXs20rAxg2xArvU',
    appId: '1:850076040984:web:f957491fe6af279ca4e86d',
    messagingSenderId: '850076040984',
    projectId: 'flutter-bootcamp-project-addcc',
    authDomain: 'flutter-bootcamp-project-addcc.firebaseapp.com',
    storageBucket: 'flutter-bootcamp-project-addcc.firebasestorage.app',
    measurementId: 'G-1D74433MB0',
  );
}
